name: finak
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  dartz: ^0.10.1
  get: ^4.6.6
  easy_localization: ^3.0.7
  equatable: ^2.0.7
  shared_preferences: ^2.3.3
  permission_handler: ^11.3.1
  page_transition: ^2.1.0
  flutter_svg: ^2.0.16
  cached_network_image: ^3.4.1
  path_provider: ^2.1.5
  flutter_launcher_icons: ^0.14.2
  image_picker: ^1.1.2
  smooth_page_indicator: ^1.2.0+3
  pretty_dio_logger: ^1.4.0
  overlay_loader_with_app_icon: ^0.0.4
  flutter_screenutil: ^5.9.3
  dotted_border: ^2.1.0
  # neww
  curved_labeled_navigation_bar: ^2.0.5
  awesome_dialog: ^3.2.1
  overlay_loading_progress: ^1.0.2
  pinput: ^5.0.1
  card_swiper: ^3.0.1
  auto_size_text: ^3.0.0
  geolocator: ^12.0.0
  geocoding:
  location: ^6.0.2
  google_maps_flutter:
  package_info_plus: ^8.1.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  firebase_core: ^3.10.1
  firebase_messaging: 
  flutter_local_notifications: ^17.1.2
  cloud_firestore: 
  firebase_auth: ^5.5.1
  firebase_storage: 
  flutter_facebook_auth: ^7.1.1
  google_sign_in: 
  photo_view: ^0.15.0
  sign_in_with_apple: ^6.1.4
  flutter_secure_storage: ^9.2.4
  intl_phone_field: ^3.2.0
 
 



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  # background_color: "#ffffff"
  image_path: "assets/images/logo.png"
  adaptive_icon_foreground: "assets/images/logo.png"
  # adaptive_icon_background: "#ffffff"


flutter:


  uses-material-design: true

  assets:
   - assets/lang/
   - assets/images/
   - assets/icons/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost.ttf